# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/olgazimina/Desktop/ui_for_particles.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1076, 806)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 1041, 781))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(840, 10, 191, 361))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_3)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 90, 151, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(10, 70, 111, 16))
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 260, 150, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 310, 81, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.frame = QtWidgets.QFrame(self.groupBox_3)
        self.frame.setGeometry(QtCore.QRect(120, 300, 51, 51))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 140, 191, 111))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.x_crd = QtWidgets.QLineEdit(self.groupBox_2)
        self.x_crd.setGeometry(QtCore.QRect(0, 20, 51, 21))
        self.x_crd.setObjectName("x_crd")
        self.y_crd = QtWidgets.QLineEdit(self.groupBox_2)
        self.y_crd.setGeometry(QtCore.QRect(70, 20, 51, 21))
        self.y_crd.setObjectName("y_crd")
        self.z_crd = QtWidgets.QLineEdit(self.groupBox_2)
        self.z_crd.setGeometry(QtCore.QRect(140, 20, 51, 21))
        self.z_crd.setObjectName("z_crd")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 0, 16, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(90, 0, 16, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(160, 0, 16, 16))
        self.label_7.setObjectName("label_7")
        self.speed_u = QtWidgets.QLineEdit(self.groupBox_2)
        self.speed_u.setGeometry(QtCore.QRect(0, 80, 51, 21))
        self.speed_u.setObjectName("speed_u")
        self.speed_v = QtWidgets.QLineEdit(self.groupBox_2)
        self.speed_v.setGeometry(QtCore.QRect(70, 80, 51, 21))
        self.speed_v.setObjectName("speed_v")
        self.speed_w = QtWidgets.QLineEdit(self.groupBox_2)
        self.speed_w.setGeometry(QtCore.QRect(140, 80, 51, 21))
        self.speed_w.setObjectName("speed_w")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(20, 60, 16, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(90, 60, 16, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(160, 60, 16, 16))
        self.label_10.setObjectName("label_10")
        self.label_mass = QtWidgets.QLabel(self.groupBox_3)
        self.label_mass.setGeometry(QtCore.QRect(130, 70, 51, 20))
        self.label_mass.setText("")
        self.label_mass.setObjectName("label_mass")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(860, 560, 150, 32))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(840, 380, 191, 91))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox.setGeometry(QtCore.QRect(10, 50, 171, 26))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 171, 31))
        self.label_2.setObjectName("label_2")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.groupBox)
        self.openGLWidget.setGeometry(QtCore.QRect(10, 0, 821, 761))
        self.openGLWidget.setObjectName("openGLWidget")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(850, 530, 131, 20))
        self.label_4.setObjectName("label_4")
        self.lineEdit_N = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_N.setGeometry(QtCore.QRect(980, 530, 51, 21))
        self.lineEdit_N.setObjectName("lineEdit_N")
        self.pushButton_SS = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_SS.setGeometry(QtCore.QRect(850, 600, 171, 32))
        self.pushButton_SS.setObjectName("pushButton_SS")
        self.pushButton_stop = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_stop.setGeometry(QtCore.QRect(860, 730, 151, 32))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.label_time = QtWidgets.QLabel(self.groupBox)
        self.label_time.setGeometry(QtCore.QRect(900, 640, 121, 31))
        self.label_time.setText("")
        self.label_time.setObjectName("label_time")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(840, 650, 61, 16))
        self.label_11.setObjectName("label_11")
        self.label_time_steps = QtWidgets.QLabel(self.groupBox)
        self.label_time_steps.setGeometry(QtCore.QRect(920, 690, 101, 31))
        self.label_time_steps.setText("")
        self.label_time_steps.setObjectName("label_time_steps")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(840, 690, 81, 31))
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1076, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Величина массы"))
        self.pushButton_2.setText(_translate("MainWindow", "Добавить частицу"))
        self.pushButton_3.setText(_translate("MainWindow", "Цвет"))
        self.label_5.setText(_translate("MainWindow", "x"))
        self.label_6.setText(_translate("MainWindow", "y"))
        self.label_7.setText(_translate("MainWindow", "z"))
        self.label_8.setText(_translate("MainWindow", "u"))
        self.label_9.setText(_translate("MainWindow", "v"))
        self.label_10.setText(_translate("MainWindow", "w"))
        self.pushButton.setText(_translate("MainWindow", "Генерация"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Верле odeint отрисовка"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Верле отрисовка"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Верле odeint"))
        self.comboBox.setItemText(3, _translate("MainWindow", "метод Верле"))
        self.comboBox.setItemText(4, _translate("MainWindow", "метод Верле (threading или multiprocessing)"))
        self.comboBox.setItemText(5, _translate("MainWindow", "метод Верле (Cython)"))
        self.comboBox.setItemText(6, _translate("MainWindow", "метод Верле (OpenCL/CUDA)"))
        self.label_2.setText(_translate("MainWindow", "Способ решения задачи:"))
        self.label_4.setText(_translate("MainWindow", "Количество частиц"))
        self.pushButton_SS.setText(_translate("MainWindow", "Солнечная система"))
        self.pushButton_stop.setText(_translate("MainWindow", "Стоп/очистить"))
        self.label_11.setText(_translate("MainWindow", "Время:"))
        self.label_12.setText(_translate("MainWindow", "Кол-во\n"
"шагов по t:"))

